// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3mjrYCNcc9OzEpCgfz4tuyVhlLbK3BK4',
    appId: '1:838833757011:web:2c4bbf01b10ba18e851fa6',
    messagingSenderId: '838833757011',
    projectId: 'chat-app-e6cf0',
    authDomain: 'chat-app-e6cf0.firebaseapp.com',
    storageBucket: 'chat-app-e6cf0.appspot.com',
    measurementId: 'G-XY6FEY8E8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSoB8o3XbIxvzMqJylT-NlBtLv4mHS1ck',
    appId: '1:838833757011:android:6a5b18b55c4a86a4851fa6',
    messagingSenderId: '838833757011',
    projectId: 'chat-app-e6cf0',
    storageBucket: 'chat-app-e6cf0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ1r3pIq1x2A2OiH7V1TVPvWKHdxGxNLE',
    appId: '1:838833757011:ios:6a23a2a8b9a0107c851fa6',
    messagingSenderId: '838833757011',
    projectId: 'chat-app-e6cf0',
    storageBucket: 'chat-app-e6cf0.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ1r3pIq1x2A2OiH7V1TVPvWKHdxGxNLE',
    appId: '1:838833757011:ios:1bfc8d30593e80bc851fa6',
    messagingSenderId: '838833757011',
    projectId: 'chat-app-e6cf0',
    storageBucket: 'chat-app-e6cf0.appspot.com',
    iosBundleId: 'com.example.scholarChat.RunnerTests',
  );
}
